version: '3.8'
services:

  php:
    container_name: grpc-php
    build:
        context: .
        dockerfile: .docker/php/Dockerfile
    working_dir: /app
    volumes:
      - './php:/app:delegated'
      - './shared:/shared:delegated'
      - "./s3:/s3"
    networks:
      - grpc

  node:
    container_name: grpc-node
    build:
        context: .
        dockerfile: .docker/node/Dockerfile
    working_dir: /app
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "rm -rf node_modules && npm install && node server.js"
    volumes:
      - './node:/app:delegated'
      - './shared:/shared:delegated'
      - "./s3:/s3"
    networks:
      - grpc

networks:
  grpc:
    name: grpc
    driver: bridge

volumes:
  s3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./s3