version: '3.8'
services:

  nginx:
    container_name: grpc-nginx
    image: nginx:1.21
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/app.conf:/etc/nginx/conf.d/app.conf"
      - "./nginx/grpc.conf:/etc/nginx/conf.d/grpc.conf"
      - "./s3:/s3"
    ports:
      - 80:80
      - 443:443
    networks:
      - grpc
    depends_on:
      - php
      - node

  php:
    container_name: grpc-php
    build:
        context: .
        dockerfile: .docker/php/Dockerfile
    working_dir: /app
    volumes:
      - './php:/app:delegated'
      - './shared:/shared:delegated'
      - "./s3:/s3"
    ports:
      - '9000:9000'
    networks:
      - grpc

  node:
    container_name: grpc-node
    build:
        context: .
        dockerfile: .docker/node/Dockerfile
    working_dir: /app
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "rm -rf node_modules && npm install && node server.js"
    volumes:
      - './node:/app:delegated'
      - './shared:/shared:delegated'
      - "./s3:/s3"
    ports:
      - '50051:50051'
    networks:
      - grpc

networks:
  grpc:
    name: grpc
    driver: bridge

volumes:
  s3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./s3